config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'ashtanga#index'
  get '/eventi' => 'eventi#index', as: :eventis
  get '/eventi/:id' => 'eventi#show', as: :eventi
  get '/galleria' => 'gallery#index', as: :galleria
  get '/tradizione' => 'ashtanga#tradizione', as: :tradizione
  get '/vinyasa' => 'ashtanga#vinyasa', as: :vinyasa
  get '/istruttore' => 'ashtanga#istruttore', as: :istruttore
  get '/classi' => 'classi#index', as: :classi
  get '/bed' => 'ashtanga#bed', as: :bed
  get '/news' => 'news#index', as: :news
  get '/news/:id' => 'news#show', as: :noti
  get '/contattaci' => 'ashtanga#contacti', as: :contacti
  # get '/news/:id' => 'noti#show', as: :news_show


end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/classi.rb
class Classi < ActiveRecord::Base
  extend FriendlyId
  friendly_id :site, use: :slugged
end

app/models/eventi.rb
class Eventi < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_attached_file :photo, styles: {
    medium: "900x675>",
    thumb: "390x210#",
    index: "523x261#"
  },
  url: "/assets/eventi/:id/:style/:id.:extension",
  path: "#{ENV['OPENSHIFT_DATA_DIR']}public/assets/eventi/:id/:style/:id.:extension"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :oraris
end

app/models/noti.rb
class Noti < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
  has_attached_file :photo, styles: {
    medium: "900x675>",
    thumb: "390x210#",
    index: "523x261#"
  },
  url: "/assets/noti/:id/:style/:id.:extension",
  path: "#{ENV['OPENSHIFT_DATA_DIR']}public/assets/noti/:id/:style/:id.:extension"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/orari.rb
class Orari < ActiveRecord::Base
  WEEK = [
    "lunedì",
    "martedì",
    "mercoledì",
    "giovedì",
    "venerdì",
    "sabato",
    "domenica"
  ]
  belongs_to :location
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  has_attached_file :photo, styles: {
    medium: "900x675>",
    thumb: "390x228#",
  },
  url: "/assets/galery/:id/:style/:id.:extension",
  path: "#{ENV['OPENSHIFT_DATA_DIR']}public/assets/galery/:id/:style/:id.:extension"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ashtanga_controller.rb
class AshtangaController < ApplicationController
  def index
    @eventi = Eventi.last
    @noti = Noti.last
  end
  def vinyasa
    @custom_title = "Il sistema dei Vinyasa"
  end
  def tradizione
    @custom_title = "La Tradizione"
  end
  def bed
    @custom_title = "Bed & Breakfast"
  end
  def contacti
    @custom_title = "Contattaci"
  end
end

app/controllers/classi_controller.rb
class ClassiController < ApplicationController
  def index
    @custom_title = "Classi e Orari"
    @locations= Location.order(created_at: :desc)
  end

  def show
    @location = Location.find(params[:id])
    @custom_title = "#{@location.name}"
  end
end

app/controllers/eventi_controller.rb
class EventiController < ApplicationController
  def index
    @custom_title = "Yoga Eventis"
    @eventis = Eventi.page(params[:page]).per(5).order('created_at DESC')
  end

  def show
    @eventi = Eventi.friendly.find(params[:id])
    @custom_title = "#{@eventi.title}"
  end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
    @custom_title = "Galleria"
    @pictures = Picture.order("position ASC").all
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  def index
    @custom_title = "Yoga News"
    @notis = Noti.page(params[:page]).per(5).order('created_at DESC')
  end

  def show
    @noti = Noti.friendly.find(params[:id])
    @custom_title = "#{@noti.title}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ashtanga_helper.rb
module AshtangaHelper
end

app/helpers/classi_helper.rb
module ClassiHelper
end

app/helpers/eventi_helper.rb
module EventiHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/ashtanga/bed.html.haml
%h1 Bed & Breakfast
.row
  = render partial: "shared/bed_carrusel"
  .col-md-7
    %p
      In una piccola collina, chiamata  Il Colle,  da cui si gode la vista dei monti Mondiego e Nerone che si svelano Imponenti di fronte  e del paesino di Piobbico che si adagia tra i due rilievi, sorge in un piccolo Borgo rurale il B&amp;B BrancaYoga. Il  Parco del Monte Nerone e le campagne limitrofe quasi selvaggie e con una bassissima antropizzazione costituiscono il luogo ideale per immergersi nella natura e godere di momenti di relax , di avventura, di sport all’aperto. Innumerevoli percorsi per la mountain bike, falesie molto apprezzate dagli amanti dell’arrampicata sportiva, percorsi speleologici nelle grotte del monte Nerone , trekking attraverso affascinanti  sentieri alla scoperta di antichi mulini, conventi abbandonati, ruderi di castelli . La visita  al Castello Brancaleoni , nell’abitato di Piobbico, ricco di storia e di arte. Ma la specialità del B&amp;B BrancaYoga è la possibilità di coniugare il contesto di cui sopra con la pratica dello Yoga, di cui Sandro Brancaleoni è appassionato e istruttore dal 1999.(Diplomato UISP). Il B&amp;B BrancaYoga in circa 200 mq ha disposizione 2 camere doppie e una tripla, due bagni, un’ampia cucina, un soggiorno e una yogashala  attrezzata per lo yoga . Si affitta il posto letto o l’intera struttura. Inoltre è possibile prenotare oltre all’alloggiamento anche le eventuali lezione di yoga.
    %p
      Per informazioni e prenotazioni  tel 348 1502714 339 8453868

app/views/ashtanga/contacti.html.haml
.row
  .col-md-3.separa
    %h1 Contattaci
    %p
      %strong Astanga Urbino
      %br (0039) 348 1502714
      %br (0039) 339 8453868
      %br brancayoga@gmail.com
  .formulario.col-md-8
    

app/views/ashtanga/index.html.haml
.row.inicio
  .col-md-4
    %a{:href => eventis_url}
      = image_tag('event.png', class: 'bloque')
      %h2 Eventi

  .col-md-4
    %a{:href => classi_url}
      = image_tag('yoga.png', class: 'bloque')
      %h2 Classi e Orari
  .col-md-4
    %a{:href => bed_url}
      = image_tag('rest.png', class: 'bloque')
      %h2 Bed & Breakfast
.row
  - if @eventi
    .col-sm-6
      .index-en
        %h2= link_to @eventi.title, eventi_path(@eventi)
        %img{ class: "img-responsive", src: "https://maps.googleapis.com/maps/api/staticmap?center=#{@eventi.location}&maptype=roadmap&zoom=17&size=523x261&sensor=true&markers=size:big%7Ccolor:red%7C#{@eventi.location}"}

  - if @noti
    .col-sm-6
      .index-en
        %h2= link_to @noti.title
        = image_tag(@noti.photo.url(:index), :class => "img-responsive")

app/views/ashtanga/istruttore.html.haml
%h1 Istruttore
.row
  .col-md-5
    =image_tag 'istruttore.jpg', :class => "img-rounded"
  .col-md-7
    %p
      Sandro Brancaleoni dal 1990 lavora come Informatore Scientifico del farmaco nella provincia di Pesaro-Urbino e contemporaneamente comincia ad interessarsi e a praticare lo Yoga.
    %p
      Nel 1999 consegue il diploma di istruttore riconosciuto UISP presso la scuola del  M°Bruno Baleotti di Bologna (metodo Parinama) ed inizia ad insegnare. Nel 2000 comincia a praticare l’Asthanga vinyasa Yoga presso Asht.
    %p
      Yoga Research Istitute diretta dal M° Lino Miele, frequentanto da allora costantemente i workshops e i ritiri . Viene autorizzato nel giugno 2011 dal M° Miele ad introdurre l’insegnamento della 1°serie. Nel 2011 interrompe l’attività di Informatore Scientifico per occuparsi a tempo pieno allo Yoga.
    %p
      Nel giugno 2013 partecipa al In-Depth Study of Astanga Yoga, organizzato dal M°Miele in collaborazione con i suoi assistenti dell’AYRI di Roma, conseguendo il diploma all’insegnamento della prima serie.

app/views/ashtanga/tradizione.html.haml
%h1
  La Tradizzione
%p
  L’Ashtanga yoga trova le sue origini nella tradizione tramandata dal saggio Vamana Rishi (Yoga Korunta) e attraverso  Guru Rama Mohan Brahmachari prima e Krishnamacharya poi arriva fino a Pattabhi Jois (1927). Pattabhi Jois riceve nel 1937 il titolo di Vidwan  e viene nominato professore e capo dipartimento di Yoga del Maharaja Sanskrit College di Mysore.
%p
  Nel 1945 viene onorato del titolo di “Yogasana Visharada”. Nel 1948 fonda l‘ Ashtanga Yoga Research Istitute. Dal 1976 al 1978 è stato professore onorario di Yoga presso il “Goovernament College of Indian Medicine”.
%p
  Pattabhi Jois  è stato uno dei grandi Yogi che ha condiviso il suo sapere con studenti di tutto il mondo.

app/views/ashtanga/vinyasa.html.haml
%h1 Il sistema dei Vinyasa
.row
  .col-md-5
    =image_tag 'jois.png', :class => "img-responsive img-rounded"
  .col-md-7
    %p
      Lo Yoga è una filosofia di vita che ha nel suo potenziale anche quello di creare un corpo ed una mente forti e sani
    %p
      La particolarità dell'Ashtanga Yoga è data dal sistema del Vinyasa (respiro e movimento). Il Vinyasa regola il respiro e garantisce una buona circolazione del sangue, garantendo corpo forte e, allo stesso tempo, leggero. Attraverso questa pratica che unisce una corretta respirazione (Ujjayi), le posture (asanas) e lo sguardo (dristi) si ottiene un controllo dei sensi e una profonda consapevolezza di se stessi fisica, psicologica e spirituale.
    %p
      Questo antico metodo è caratterizzato da una sequenza di posizioni concatenate tra loro e sincronizzate con il respiro. Il respiro unisce il corpo con la parte più profonda della mente - lo spirito - e lo spirito della pratica dell'Ashtanga è il respiro. L'Ashtanga Yoga va praticato nel suo corretto ordine sequenziale meticolosamente rispettato perchè ogni asana (postura) è una preparazione per la successiva e sviluppa la forza e l'equilibrio per andare avanti.
    %p
      Acquisendo la capacità di un respiro lungo e profondo la mente diviene calma e concentrata, i pensieri si fermano e ciascun movimento fluisce gentilmente e accuratamente da un'asana all'altra. Quando respiro e movimento fluiscono senza sforzo ed in perfetta armonia, allora la pratica dell'Ashtanga Yoga trascende la consapevolezza e si evolve nella leggerezza di una meditazione in movimento.
    %p
      Il respiro, Ujjayi, è il cuore di questa disciplina. Sincronizzato con il movimento (vinyasa) e praticando Mula e Uddiyana Bandhas (chiusure) si produce un intenso calore il quale purifica i muscoli e gli organi interni eliminando, tramite la sudorazione, le tossine e liberando ormoni benefici e sali minerali che sono un ottimo alimento per il corpo. L'espirazione è un movimento verso il Dio e l'inspirazione rappresenta un assorbimento da Dio. Secondo gli insegnamenti di Sri K. Pattabhi Jois "il Respiro è Vita". Allungare il respiro, con la pratica, allunga la Vita. La consapevolezza del respiro porta leggerezza, elasticità e forza nei movimenti, aumenta la sensibilità e la ricezione agli stimoli esterni.... per conoscere se stessi.
    %p
      La pratica: si dice che dove non c'è sforzo non ci può essere beneficio. Forza, stamina e sudore sono gli aspetti unici e particolari di questa antica e tradizionale forma di yoga che apparentemente sembra contradire la visione occidentale dello yoga in genere. Questa pratica così esigente richiede un notevole sforzo, sviluppa, però, una grande energia vitale che circola attraverso il corpo, rafforzando e purificando il sistema nervoso. La mente allora diventa lucida, chiara e precisa.

app/views/classi/index.html.haml
%h1 Classi e Orari
%h2 I corsi si svolgono
- @locations.each_slice(2) do |loc|
  .row
    - loc.each do |location|
      .col-sm-6
        .location.oraricont
          = image_tag('map.png', :class => 'bloque img-responsive map')
          %h2= location.name
          .row
            - (0..6).to_a.each do |d|
              .col-sm-1
                = render partial: 'shared/day', locals: { oraris: location.oraris.where(day: d).order(from: :asc), day: Orari::WEEK[d][0].upcase }

app/views/eventi/_s_picture.html.haml
.row.eventi
  .col-md-4
    %img{ class: "bloque img-thumbnail", src: "https://maps.googleapis.com/maps/api/staticmap?center=#{eventi.location}&maptype=roadmap&zoom=17&size=390x210&sensor=true&markers=size:big%7Ccolor:red%7C#{eventi.location}"}
  .col-md-8
    %h2= link_to eventi.title, eventi_path(eventi)
    %p= truncate(eventi.description, length: 400)
    %span
      %i.glyphicon.glyphicon-calendar
      = eventi.date.strftime("%d/%m/%Y %H:%M %p")
    %span.pull-right
      %i.glyphicon.glyphicon-map-marker
      = eventi.location

app/views/eventi/_w_picture.html.haml
.row.eventi
  .col-md-4
    %img{ class: "bloque img-thumbnail", src: "https://maps.googleapis.com/maps/api/staticmap?center=#{eventi.location}&maptype=roadmap&zoom=17&size=390x210&sensor=true&markers=size:big%7Ccolor:red%7C#{eventi.location}"}
  .col-md-4
    = image_tag(eventi.photo(:thumb), class: "bloque img-responsive img-thumbnail")
  .col-md-4
    %h2= link_to eventi.title, eventi_path(eventi)
    %p= truncate(eventi.description, length: 150)
    %p
      %i.glyphicon.glyphicon-calendar
      = eventi.date.strftime("%d/%m/%Y %H:%M %p")
    %p
      %i.glyphicon.glyphicon-map-marker
      = eventi.location

app/views/eventi/index.html.haml
%h1 Eventi
- @eventis.each do |eventi|
  - if eventi.photo.exists?
    = render partial: 'w_picture', locals: {eventi: eventi}
  - else
    = render partial: 's_picture', locals: {eventi: eventi}
  %hr
  = paginate @eventis

app/views/eventi/show.html.haml
.row.eventis
  .col-md-4
    %img{ class: "bloque img-thumbnail img-responsive", src: "https://maps.googleapis.com/maps/api/staticmap?center=#{@eventi.location}&maptype=roadmap&zoom=17&size=300x200&sensor=true&markers=size:big%7Ccolor:red%7C#{@eventi.location}"}

  .col-md-8
    %h1= @eventi.title
    %span
      %i.glyphicon.glyphicon-calendar
      = @eventi.date.strftime("%d/%m/%Y %H:%M %p")
    %span.pull-right
      %i.glyphicon.glyphicon-map-marker
      = @eventi.location
    = simple_format(@eventi.description)
    - if @eventi.photo
      = image_tag(@eventi.photo.url(:medium), class: "bloque img-thumbnail")

app/views/gallery/index.html.haml
.blueimp-gallery.blueimp-gallery-controls#blueimp-gallery
  .slides
  %h3.title
  %a.prev
    <
  %a.next
    >
  %a.close
    x
  %a.play-pause
  %ol.indicator
%h1 Galleria
- @pictures.each_slice(3) do |photos|
  .row#links
    - photos.each do |photo|
      .col-sm-4.galleria
        %a{href: photo.photo.url(:medium), title: photo.title, :"data-gallery" => "ashtanga-gallery"}
          = image_tag(photo.photo.url(:thumb), :class => "img-responsive img-thumbnail")
%link{:rel => "stylesheet", :href => "/css/blueimp-gallery.min.css"}
%script{:src => "/js/jquery.blueimp-gallery.min.js"}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:"http-equiv" => "X-UA-Compatible", :content => "IE=edge"}
    %meta{:name => 'viewport', :content => "width=device-width, initial-scale=1"}

    - if !@custom_title
      %title Astanga Yoga Urbino
    - else
      %title= "#{@custom_title} | Astanga Yoga Urbino"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render partial: "shared/menu"
    = render partial: "shared/carrusel"
    %div.container.lb-blanco
      = yield
    = render partial: "shared/footer"

app/views/news/index.html.haml
%h1 Yoga News
- @notis.each do |noti|
  .row.eventi
    .col-md-4
      - if noti.photo
        = image_tag(noti.photo.url(:thumb), :class => "img-responsive img-thumbnail")
    .col-md-8
      %h2= link_to noti.title, noti_path(noti)
      %p= truncate(noti.content, length: 300)
      %span
        %i.glyphicon.glyphicon-calendar
        = noti.created_at.strftime("%d/%m/%Y %H:%M %p")
  %hr
  = paginate @notis

app/views/news/show.html.haml
.row.eventis
  .col-md-4
    = image_tag(@noti.photo.url(:thumb), class: "bloque img-responsive img-thumbnail")
  .col-md-8
    %h1= @noti.title
    %span
      %i.glyphicon.glyphicon-calendar
      = @noti.created_at.strftime("%d/%m/%Y %H:%M %p")
    = simple_format(@noti.content)
    - if @noti.photo
      = image_tag(@noti.photo.url(:medium), class: "bloque img-responsive img-thumbnail")

app/views/shared/_bed_carrusel.html.haml
.col-md-5
  .carousel.slide#bedCarousel{:"data-ride" => "carousel"}
    %ol.carousel-indicators
      %li{ :"data-target" => "#bedCarousel", :"data-slide-to" => "0", :class => "active"}
      %li{ :"data-target" => "#bedCarousel", :"data-slide-to" => "1"}
      %li{ :"data-target" => "#bedCarousel", :"data-slide-to" => "2"}
      %li{ :"data-target" => "#bedCarousel", :"data-slide-to" => "3"}
      %li{ :"data-target" => "#bedCarousel", :"data-slide-to" => "4"}
      %li{ :"data-target" => "#bedCarousel", :"data-slide-to" => "5"}
    .carousel-inner{role: "listbox"}
      .active.item
        = image_tag("vista_frontale.jpg", :class => "img-responsive img-astanga")
      .item
        = image_tag("cucina.jpg", :class => "img-responsive img-astanga")
      .item
        = image_tag("soggiorno_1.jpg", :class => "img-responsive img-astanga")
      .item
        = image_tag("soggiorno_2.jpg", :class => "img-responsive img-astanga")
      .item
        = image_tag("cammera_doppia.jpg", :class => "img-responsive img-astanga")
      .item
        = image_tag("cammera_tripla.jpg", :class => "img-responsive img-astanga")

app/views/shared/_carrusel.html.haml
.container.full
  .slide-holder
  .carousel.slide#ashtangaCarousel{:"data-ride" => "carousel"}
    %ol.carousel-indicators
      %li{ :"data-target" => "#ashtangaCarousel", :"data-slide-to" => "0", :class => "active"}
      %li{ :"data-target" => "#ashtangaCarousel", :"data-slide-to" => "1"}
      %li{ :"data-target" => "#ashtangaCarousel", :"data-slide-to" => "2"}
      %li{ :"data-target" => "#ashtangaCarousel", :"data-slide-to" => "3"}
      %li{ :"data-target" => "#ashtangaCarousel", :"data-slide-to" => "4"}
    .carousel-inner{role: "listbox"}
      .active.item
        = image_tag("banner.png", :class => "img-responsive img-astanga")
      .item
        = image_tag("banner1.png", :class => "img-responsive img-astanga")
      .item
        = image_tag("banner2.png", :class => "img-responsive img-astanga")
      .item
        = image_tag("banner3.png", :class => "img-responsive img-astanga")
      .item
        = image_tag("banner4.png", :class => "img-responsive img-astanga")

app/views/shared/_day.html.haml
.row
  .col-sm-7.letras
    %h3= day
- oraris.each do |orari|
  .row
    .from-to
      %p= orari.from.strftime("%H:%M")
      %p= orari.to.strftime("%H:%M")

app/views/shared/_footer.html.haml
.footer
  .container
    .row
      .col-sm-4.barrita
        %h3 Siti da segnalare
        %ul.list-unstyled
          %li
            %a{:href => "http://www.astanga.it/", :target => "_blank"} Astanga Yoga Research Institute
          %li
            %a{:href => "http://www.astangamilano.it/", :target => "_black"} Ashtanga Yoga Milano
          %li
            %a{:href => "http://www.hathayoga.it/", :target => "_black"} Parinama Yoga
          %li
            %a{:href => "http://www.ashtangayogariccione.it/", :target => "_black"} Ashtanga Yoga Riccione
      .col-sm-4.barrita
        %h3 Contattaci
        %ul.list-unstyled
          %li (+39) 348-150-2714
          %li (+39) 339-845-3868
          %li brancayoga@gmail.com
          %li
            %a{:href => "https://www.facebook.com/ashtangayogaurbino", :target => "_blank"} Facebook Ashtanga Yoga Urbino
  .creditos
    .container
      = "&copy;#{Time.now.year} Ashtanga Urbino".html_safe
      %br
      Grafica:
      %a{:href => "https://www.abrahmatansini.com", :target => "_blank"} Abrahma Tansini
      \/ Programazione:
      %a{:href => "https://mijailr.com", :target => "_blank"} Mijail Rondon

app/views/shared/_menu.html.haml
.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      %button{ :class => "navbar-toggle collapsed", :"data-toggle" => "collapse", :"data-target" => "#astanga-menu" }
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse#astanga-menu
      %ul.nav.navbar-nav
        %li
          = link_to "Home", root_path
        %li.dropdown
          %a{:href => "#", :class => "dropdown-toggle", :"data-toggle" => "dropdown", :role => "button", :"aria-haspopup" => "false", :"aria-expanded" => "false"}
            Il Metodo
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to "La Tradizione", tradizione_path
            %li
              = link_to "Il Sisteme dei Vinyasa", vinyasa_path
            %li
              = link_to "Istruttore", istruttore_path
        %li
          = link_to "Classi e Orari", classi_path
        %li
          = link_to "Bed & Breakfast", bed_path
        %li
          = link_to "Eventi", eventis_path
        %li
          = link_to "News", news_path
        %li
          = link_to "Galleria", galleria_path
        %li
          = link_to "Contattaci", contacti_path